### ISSUE TITLE
laravel 5.4报错

### ISSUE THREAD

**Issue by cnsecer** [overtrue/laravel-uploader#10]
Undefined index: filters (View: /home/vagrant/Code/wxapp/resources/views/vendor/uploader/images.blade.php) (View: /home/vagrant/Code/wxapp/resources/views/vendor/uploader/images.blade.php)

**Comment by overtrue** [comment]
@cnsecer 按我的 https://github.com/overtrue/laravel-uploader/commit/59e2e5e4273c84bb5d73f12117dd9ac8de251a79  改一下 helpers.php 看看，没问题我就发版了

**Comment by cnsecer** [comment]
可以了

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-uploader/releases/tag/0.0.2

**Comment by wh469012917** [comment]
刚刚从composer刚拉下来的版本，还是报同样的错误。看了下helpers，已经是修改过的了。不知道啥回事

**Comment by overtrue** [comment]
@wh469012917 composer info overtrue/laravel-uploader 贴上来看看

**Comment by wh469012917** [comment]
![image](https://user-images.githubusercontent.com/10496478/27572859-043be33e-5b41-11e7-8900-bdab577070fc.png)

**Comment by wh469012917** [comment]
@overtrue 刚刚直接从https://github.com/overtrue/laravel-uploader/releases/tag/0.0.2上面下载代码，然后覆盖到vendor里面，然后重新php artisan vendor:publish之后，清除缓存后，还是报同样的错误。
方便再测试一下不？
框架：Laravel5.4
系统：Ubuntu16.04
浏览器：Chrome 58.0.3029.110

**Comment by overtrue** [comment]
报啥错误啊

**Comment by wh469012917** [comment]
Undefined index: filters (View: /var/www/html/tasks/resources/views/vendor/uploader/images.blade.php) (View: /var/www/html/tasks/resources/views/vendor/uploader/images.blade.php)

**Comment by overtrue** [comment]
你原来的生成的文件没删除吧？

**Comment by overtrue** [comment]
vendor publish 又不会覆盖

**Comment by wh469012917** [comment]
肯定删除了才再vendor publish的，而且刚才重新新建了一个laravel项目，再测试也是报这个错误

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-uploader/blob/master/src/LaravelUploader/helpers.php#L14

**Comment by overtrue** [comment]
我已经在这里加了这个，不应该会是报它不存在啊

**Comment by wh469012917** [comment]
我在这里直接dd的结果，确实不存在filters
```php
$name = isset($name) ? $name : 'images';
$strategy = isset($strategy) ? $strategy : 'default';
dd(uploader_strategy($strategy));
```

结果：
```php
array:5 [
  "input_name" => "file"
  "mimes" => array:4 [▶]
  "disk" => "public"
  "directory" => "{Y}/{m}/{d}"
  "max_file_size" => "2m"
]
```

**Comment by overtrue** [comment]
@wh469012917 应该好了

**Comment by wh469012917** [comment]
知道原因了，在配置文件中少了filters这个选项吧

**Comment by overtrue** [comment]
@wh469012917 是，但是内部也应该兼容这样的情况存在，你升级到 0.0.4 看看

**Comment by wh469012917** [comment]
ok，谢谢了
