### ISSUE TITLE
如何设置默认文件？

### ISSUE THREAD

**Issue by bestony** [overtrue/laravel-uploader#14]
# 预期动作

```
 @uploader('file', ['name' => 'image','data'=>$directory->image])
```
或某种其他设置可以正常输出结果。

# 当前动作

```
 @uploader('file', ['name' => 'image','data'=>$directory->image])
```
这样的设置没有任何效果。
# 可能的解决方案

无

# 内容

无法设置默认的文件。

# 图示
![snip20170820_2](https://user-images.githubusercontent.com/13283837/29492818-cf8df970-85ba-11e7-8c73-d68e9c1beb2c.png)
![snip20170820_4](https://user-images.githubusercontent.com/13283837/29492819-cf9c757c-85ba-11e7-960c-02db978d932d.png)

## 环境

* 使用的版本:"laravel/framework": "5.5.*","overtue/laravel-uploader": "^0.0.7"
* 环境名和版本信息: PHP 7.1 on Nginx 1.12.0_1
* 操作系统类型和版本: macOS 10.12.6

# 相关代码
https://github.com/overtrue/laravel-uploader/blob/dc034a1bea7938d053aa4bf41271dce0873d3ded/src/config/uploader.php#L29

https://github.com/overtrue/laravel-uploader/blob/dc034a1bea7938d053aa4bf41271dce0873d3ded/src/resources/views/file.blade.php#L6

**Comment by overtrue** [comment]
```php
 @uploader('file', ['name' => 'image', 'file'=>$directory->image])
```
