### ISSUE TITLE
file.upload 路由名称未找到

### ISSUE THREAD

**Issue by gankbat** [overtrue/laravel-uploader#19]
我的laravel 的版本是5.5.* ,包的版本是 dev-master (能发布下最新的么,默认安装的0.0.7的)
引入资源文件
@uploader('assets')
![image](https://user-images.githubusercontent.com/22650353/38683474-1a5ebbb2-3ea0-11e8-8b5a-539b4b3ef1cc.png)

然后报错
``
"errors": {
        "message": "Route [file.upload] not defined.
}
``
查了下路由列表
![image](https://user-images.githubusercontent.com/22650353/38683835-f16fea54-3ea0-11e8-84fb-4d8d906a635d.png)

然后找到了这行.....
https://github.com/overtrue/laravel-uploader/blob/d8de8116ba8e4421192a445ef85c2e5dd1bff78f/src/LaravelUploader/LaravelUploader.php#L23

试了一下 name 改成 as 可以了

![image](https://user-images.githubusercontent.com/22650353/38683982-4284bd52-3ea1-11e8-9b94-9a2d8a26a9bb.png)

![image](https://user-images.githubusercontent.com/22650353/38683965-3839ee4e-3ea1-11e8-85e3-c924c4c7b3a0.png)

@overtrue

**Comment by overtrue** [comment]
哈哈，我来改一下

**Comment by overtrue** [comment]
已经修复
