### ISSUE TITLE
variable URL not defined

### ISSUE THREAD

**Issue by ZiarAdjel** [overtrue/laravel-uploader#22]
hi, i get this code in my page
`data-item-template="<img src='{URL}' />"`

and my uploaded images in folder storage/app/public/uploads but my img url like this

`<img src="http://localhost/storage/uploads/oYtVx6EDCP8NWUyY9JKfQK4JjPnfwdE7v0qWDtGk.jpg">`
how to fix that

**Comment by overtrue** [comment]
`./artisan storage:link`

> https://laravel.com/docs/5.6/structure#the-storage-directory
