### ISSUE TITLE
请问对各类上传漏洞会有计划吗？

### ISSUE THREAD

**Issue by wqsacy** [overtrue/laravel-uploader#35]
首先非常感谢你的easywechat，为了表达支持，早已经购买了教程，虽然文档已经很详细了！😂

PHP有很多上传的漏洞，比如任意文件上传漏洞，抓包修改MIME绕开验证，虽然大部分的路径都屏蔽了对应的执行权限，但是比如JS代码这些就很难处理，一个图片 include 其他txt这种也不是没有可能性，所以在上传这块一直不知道如何处理，才能杜绝此类漏洞或者说潜在威胁。

**Comment by overtrue** [comment]
安全问题一般没有银弹能一劳永逸的解决，需要从各个角度去做好防护，输入端做好类型检查，MIME 校验，系统层面做好目录权限控制，上传后附件的使用也要做好限制和过滤。
